-- Table containing Conferences
CREATE TABLE reserves.CONFERENCES(
  ID_CONF SERIAL PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  TOPIC VARCHAR(140) NOT NULL,
  ROOM_NUMBER CHAR(5) NOT NULL,
  PARTICIPANTS_NUM INT NOT NULL,
  CONF_DATE_FROM DATE NOT NULL,
  CONF_DATE_TO DATE NOT NULL
);

--Connection between talks and conferences many to many
CREATE TABLE reserves.CONFERENCES_TALKS (
  ID_CONF_TALKS SERIAL PRIMARY KEY,
  ID_CONF BIGINT NOT NULL,
  ID_TALK BIGINT NOT NULL);

--Table of Talks
CREATE TABLE reserves.TALKS (
  ID_TALK SERIAL PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  PRESENTER_NAME VARCHAR(30) NOT NULL,
  ID_TALK_TYPE BIGINT NOT NULL
);

--Table of Types of talks
CREATE TABLE  reserves.DICT_TALK_TYPES (
  ID_TALK_TYPE SERIAL PRIMARY KEY,
  TALK_TYPE_NAME VARCHAR(30)
);

-- Creating references between tables
ALTER TABLE reserves.CONFERENCES_TALKS ADD FOREIGN KEY (ID_CONF) REFERENCES reserves.CONFERENCES(ID_CONF);
ALTER TABLE reserves.CONFERENCES_TALKS ADD FOREIGN KEY (ID_TALK) REFERENCES reserves.TALKS(ID_TALK);
ALTER TABLE reserves.TALKS ADD FOREIGN KEY (ID_TALK_TYPE) REFERENCES reserves.DICT_TALK_TYPES(ID_TALK_TYPE);

-- Creating index for the database
CREATE INDEX IDX_CONF_ID_CONF ON reserves.CONFERENCES(ID_CONF);
CREATE INDEX IDX_CONF_CONF_DATE ON reserves.CONFERENCES(CONF_DATE);
CREATE INDEX IDX_TALKS_ID_TALK ON reserves.TALKS(ID_TALK);
CREATE INDEX IDX_TALKS_ID_TALK_TYPE ON reserves.TALKS(ID_TALK_TYPE);
